// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// StableMarriageAlgo
List StableMarriageAlgo(DataFrame prefA_R, DataFrame prefB_R);
RcppExport SEXP _StableMarriage_StableMarriageAlgo(SEXP prefA_RSEXP, SEXP prefB_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type prefA_R(prefA_RSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type prefB_R(prefB_RSEXP);
    rcpp_result_gen = Rcpp::wrap(StableMarriageAlgo(prefA_R, prefB_R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StableMarriage_StableMarriageAlgo", (DL_FUNC) &_StableMarriage_StableMarriageAlgo, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_StableMarriage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
